### ISSUE TITLE
Possible false positives during validation

### ISSUE THREAD

**Issue by nicolas-lang** [Nexela/Factorio-luacheckrc#17]
While performing [validations](https://github.com/nicolas-lang/Factorio.LongWarehouses/runs/2868532023) for [my mod](https://github.com/nicolas-lang/Factorio.LongWarehouses/) i have encountered a couple of warnings that i consider false-positives/incorrect

**the following issues would be in the [data stage](https://lua-api.factorio.com/latest/Data-Lifecycle.html) in sub-files included by require statements**

- "accessing undefined variable mods"
based on the [data stage documentation](https://lua-api.factorio.com/latest/Data-Lifecycle.html) mods is valid & exposed.
full message
`compatibility/krastorio2.lua:1:4: (W113) accessing undefined variable mods`
related line
`if mods["some-modname"] then`

- "accessing undefined variable data"
full message
`lib/data_util.lua:31:32: (W113) accessing undefined variable data`
based on the [data stage documentation](https://lua-api.factorio.com/latest/Data-Lifecycle.html) data is valid & exposed.
related line
`for name, technology in pairs(data.raw.technology) do`

- "accessing undefined variable circuit_connector_definitions" and "accessing undefined variable logistic_chest_opened_duration"
they should be valid globals, even though i failed to find documentation on them
full message
`prototypes/warehouse_entity.lua:144:32: (W113) accessing undefined variable circuit_connector_definitions`
`prototypes/warehouse_entity.lua:154:27: (W113) accessing undefined variable logistic_chest_opened_duration`
related line
`circuit_connector_sprites = circuit_connector_definitions["pump"].sprites,`
`whEnt.opened_duration = logistic_chest_opened_duration`

**the following issues would be in the [control stage](https://lua-api.factorio.com/latest/Data-Lifecycle.html)**

- "setting non-standard global variable \_"
based on my best knowledge the best practice to discard unwanted return values would be to assign them to \_
full message
`control.lua:268:2: (W111) setting non-standard global variable _`
related line
`_ , whType = lib_warehouse.checkEntity(entity)`
_not 100% sure about this one_

the undefined variable issues could be fixed by `local variable_name = _G.variable_name` but i would consider that redundant and since data is also set as read_global in the check settings I would assume the warning to be unintended

**Comment by muppet9010** [comment]
@nicolas-lang 
I can't speak for Nexela, but the below is based on the years I've been using this.


### Data Stage - mods and data
The usage of Factorio data stage globals has been restricted as it is currently.
In the lua parser file the section variable `factorio_data` covers the globals `mods` and `data` that you mention: https://github.com/Nexela/Factorio-luacheckrc/blob/master/.luacheckrc#L411-L427
This `factorio_data` section variable is applied to the `STD_DATA` and `STD_BASE_DATA` file variables which cover the `base` and `core` mods revelent files, plus any custom mods files in the below locations (relevant to your query(: https://github.com/Nexela/Factorio-luacheckrc/blob/master/.luacheckrc#L66-L74
So historically and currently the warnings about the `mods` and `data` globals are expected to me.


### Data Stage - circuit_connector_definitions and logistic_chest_opened_duration
The `circuit_connector_definitions` Lua global is populated by `core\lualib\circuit-connector-sprites.lua`. This is loaded by default from the `core\data.lua` file. So yes this is currently a default Lua global in current Factorio version.
The `logistic_chest_opened_duration` looks to be populated as a Lua global by `base\prototypes\entity\entities.lua`. This is loaded by default from the `base\data.lua` file. So yes this is currently also a default Lua global in current Factorio version.

There are likely a lot of these default added Factorio Lua globals I suspect. But I won't go hunting for them.

If Nexula doesn't object I will add these 2 in later. He will remove them later if he's unhappy I am sure.


###  Control Stage - "_" global
The usage of any other global Lua variable will raise a warning as this luacheck deems them all "bad". So I'm not surprised that "_" is included here as its still a global Lua variable.

**Comment by Nexela** [comment]
Everything above is true! All files default to control stage unless otherwise declared.

Well I did a thing
I added `/compatibility/'` and `/lib/data*` as data files  Not sure how much I like this as 
`/prototypes/compatibility` and `/data/util.lua` or `/lib/data/util.lua` would be much better paths.

@muppet9010 I added a factorio_base_data_common std to add some common data stage globals to until either of us can come up with a better way to do it.  Its not perfect but it will work.  It might even make the most sense clean and update the existing data globals and add them straight to the data stage files.  Thoughts?

As to `_`  you should be `local`ing all the things.   But if you really want a throwaway global you can use `__` now.

I haven't tested any of this but @nicolas-lang let me know if it works a little better for you.

**Comment by nicolas-lang** [comment]
Hi Nexela,
Hi muppet,
thanks for looking into my issues, with your changes and also with your comments it behaves now much more like I would expect ( and also have I changed my expectations slightly based on your comments)

based on your replies i would like to add 2 additional comments:

**File Structure**
I have no clear preference, it is not _required_ that the files are structured like they are, I have just tried to adapt a structure that seemed like a best practice based on what other modders created... 
If there is a structure that makes sense and allows a decent distinction between the different data stages, and shared files between stages, I am happy to adapt, It just seems like there is no clear guideline yet, neither in the wikki nor here. and the "base" mod is also a mess in this regard...

**local'ing all the things**
While I understand and agree, I am slightly confused:
This is allowed
```
function myDemo(myTable)
	for _, value in pairs(myTable) do
		log(value)
	end
end
```
while this fails:

```
function myDemo2A()
	return 'Hello','World'
end

function myDemo2B()
	local value
	_, value = myDemo2A()
end
```

to me this seems inconsistant, either both shoudl fail, or both should pass... what am I missing here ?

**Comment by muppet9010** [comment]
@Nexela Tbh I do very little around existing prototype manipulation so have never hit this issue. The challenge as I see it is working out (without huge effort) which of the stds.factorio_base_data Lua globals you already have listed are valid in a mods data stage. As its not arisen for years personally I'd be lazy and leave it how you have it now, just adding odd other ones if they are ever hit by someone.


@nicolas-lang The 2 variables defined as part of the `for` iterator `_` and `value` in your example are by default locally scoped to only the for functions operation. So they are locals in your example.
```
function myDemo(myTable)
	for _, value in pairs(myTable) do
		log(value)
	end
	print(value) -- This would have value == nil as its scoped to within the for's do>end.
end
```

Note Nexula added double underscore as an ignored global, not a single underscore.

In terms of folder structure I tend to put everything data related in prototypes as separate files and just link to them from the main data.lus / data-updates.lua, etc. Although I have had very few update or final files before and never really cases where I handle the same prototype in multiple data loading stages.
