### ISSUE TITLE
(W311) value assigned to variable data is unused

### ISSUE THREAD

**Issue by ZwerOxotnik** [Nexela/Factorio-luacheckrc#21]
```lua
local data = global.players[player_index]
if data then
  foobar(player_index)
  data = nil -- (W311) value assigned to variable data is unused
end
```

Is it possible to do something with that to avoid it? Except this:
```lua
global.players[player_index] = nil
```

**Comment by Nexela** [comment]
That code doesn't erase the table

https://stackoverflow.com/questions/26138546/delete-variable-by-reference-in-lua

**Comment by ZwerOxotnik** [comment]
Ah, thank you. I understand it now, my bad.
